/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.3 model.gltf
Author: COOL601 (https://sketchfab.com/COOL601)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/mclaren-mp4-12c-ultimate-80f19f7f5aac428985356987769538fe
Title: Mclaren MP4-12C Ultimate
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export default function Toy2(props) {
  const { nodes, materials } = useGLTF('/models/mclaren/model.gltf')
  return (
    <group {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]} scale={0.648}>
        <group rotation={[Math.PI / 2, 0, 0]}>
          <group position={[-0.07, -0.089, 2.557]}>
            <group position={[0, 0.409, -2.749]} rotation={[-1.571, 0, 0]}>
              <group position={[0, -0.032, -0.408]} rotation={[Math.PI / 2, 0, 0]}>
                <mesh geometry={nodes.Object_6.geometry} material={materials['Paint.001']} />
                <mesh geometry={nodes.Object_7.geometry} material={materials['Matte__FF000000_.001']} />
                <mesh geometry={nodes.Object_8.geometry} material={materials.koplamp_binnen} />
                <mesh geometry={nodes.Object_9.geometry} material={materials['cockpit__spec_.001']} />
                <mesh geometry={nodes.Object_10.geometry} material={materials['Matte__FF999999_.001']} />
                <mesh geometry={nodes.Object_11.geometry} material={materials['leather__spec_.001']} />
                <mesh geometry={nodes.Object_12.geometry} material={materials.stitches} />
                <mesh geometry={nodes.Object_13.geometry} material={materials['mesh2__spec_.001']} />
                <mesh geometry={nodes.Object_14.geometry} material={materials.spiegels} />
                <mesh geometry={nodes.Object_15.geometry} material={materials.Glass} />
                <mesh geometry={nodes.Object_16.geometry} material={materials['badges__spec_.001']} />
                <mesh geometry={nodes.Object_17.geometry} material={materials['carbonint__spec_.001']} />
                <mesh geometry={nodes.Object_18.geometry} material={materials['misc__spec_.001']} />
                <mesh geometry={nodes.Object_19.geometry} material={materials['vehiclelights128.001']} />
                <mesh geometry={nodes.Object_20.geometry} material={materials['vehiclelights1.001']} />
                <mesh geometry={nodes.Object_21.geometry} material={materials['vehiclelights2.001']} />
                <mesh geometry={nodes.Object_22.geometry} material={materials['vehiclelights3.001']} />
                <mesh geometry={nodes.Object_23.geometry} material={materials.binnen_koplamp} />
                <mesh geometry={nodes.Object_24.geometry} material={materials['steeringwheel__s.001']} />
                <mesh geometry={nodes.Object_25.geometry} material={materials['water__spec_.001']} />
                <mesh geometry={nodes.Object_26.geometry} material={materials['bumper_frame__sp.001']} />
                <mesh geometry={nodes.Object_27.geometry} material={materials['Matte__FF00001.001']} />
                <mesh geometry={nodes.Object_28.geometry} material={materials['Matte__FF00002.001']} />
                <mesh geometry={nodes.Object_29.geometry} material={materials['Matte__BA000000_.001']} />
                <mesh geometry={nodes.Object_30.geometry} material={materials['Material.003']} />
                <mesh geometry={nodes.Object_31.geometry} material={materials['guages__spec_.001']} />
                <mesh geometry={nodes.Object_32.geometry} material={materials['carpet__spec_.001']} />
                <mesh geometry={nodes.Object_33.geometry} material={materials['mclarenint__spec.001']} />
                <mesh geometry={nodes.Object_34.geometry} material={materials.ANgle_eye_inside} />
                <mesh geometry={nodes.Object_35.geometry} material={materials.angle_eyes} />
                <mesh geometry={nodes.Object_36.geometry} material={materials.Carbon} />
                <mesh geometry={nodes.Object_37.geometry} material={materials['Carbon.001']} />
                <mesh geometry={nodes.Object_38.geometry} material={materials['Material.069']} />
                <mesh geometry={nodes.Object_39.geometry} material={materials['Material.070']} />
                <mesh geometry={nodes.Object_40.geometry} material={materials['Material.008']} />
                <mesh geometry={nodes.Object_41.geometry} material={materials['Material.009']} />
                <mesh geometry={nodes.Object_42.geometry} material={materials['Material.036']} />
                <mesh geometry={nodes.Object_43.geometry} material={materials['Material.004']} />
                <mesh geometry={nodes.Object_44.geometry} material={materials['Material.005']} />
                <mesh geometry={nodes.Object_45.geometry} material={materials['Material.016']} />
                <mesh geometry={nodes.Object_46.geometry} material={materials['Material.017']} />
                <mesh geometry={nodes.Object_47.geometry} material={materials.Exhaust} />
                <mesh geometry={nodes.Object_48.geometry} material={materials.Exhaust_inside} />
                <mesh geometry={nodes.Object_49.geometry} material={materials['Material.010']} />
                <mesh geometry={nodes.Object_50.geometry} material={materials['Material.074']} />
                <mesh geometry={nodes.Object_51.geometry} material={materials.mclaren_logo} />
              </group>
            </group>
            <group position={[1.378, 0.527, -0.612]} rotation={[-1.571, 0, 0]}>
              <group position={[-1.378, 2.104, -0.526]} rotation={[Math.PI / 2, 0, 0]}>
                <mesh geometry={nodes.Object_54.geometry} material={materials['Silver_METAL.004']} />
                <mesh geometry={nodes.Object_55.geometry} material={materials['Tires2.004']} />
                <mesh geometry={nodes.Object_56.geometry} material={materials['SCUDO_Yellow.004']} />
                <mesh geometry={nodes.Object_57.geometry} material={materials['Red_METAL.004']} />
                <mesh geometry={nodes.Object_58.geometry} material={materials['BRAKES_4K.004']} />
                <mesh geometry={nodes.Object_59.geometry} material={materials['Black_Metal.004']} />
                <mesh geometry={nodes.Object_60.geometry} material={materials['Black_METAL1.004']} />
                <mesh geometry={nodes.Object_61.geometry} material={materials['koplamp_binnen.006']} />
                <mesh geometry={nodes.Object_62.geometry} material={materials['mclaren_logo.003']} />
              </group>
            </group>
            <group position={[-1.401, 0.527, -0.621]} rotation={[-1.571, 0, 0]}>
              <group position={[1.401, 2.095, -0.526]} rotation={[Math.PI / 2, 0, 0]}>
                <mesh geometry={nodes.Object_65.geometry} material={materials['Silver_METAL.003']} />
                <mesh geometry={nodes.Object_66.geometry} material={materials['Tires2.003']} />
                <mesh geometry={nodes.Object_67.geometry} material={materials['SCUDO_Yellow.003']} />
                <mesh geometry={nodes.Object_68.geometry} material={materials['Red_METAL.003']} />
                <mesh geometry={nodes.Object_69.geometry} material={materials['BRAKES_4K.003']} />
                <mesh geometry={nodes.Object_70.geometry} material={materials['Black_Metal.003']} />
                <mesh geometry={nodes.Object_71.geometry} material={materials['Black_METAL1.003']} />
                <mesh geometry={nodes.Object_72.geometry} material={materials['koplamp_binnen.004']} />
                <mesh geometry={nodes.Object_73.geometry} material={materials['mclaren_logo.002']} />
              </group>
            </group>
            <group position={[1.403, 0.526, -4.885]} rotation={[-1.571, 0, 0]}>
              <group position={[-1.403, -2.168, -0.526]} rotation={[Math.PI / 2, 0, 0]}>
                <mesh geometry={nodes.Object_76.geometry} material={materials['Silver_METAL.005']} />
                <mesh geometry={nodes.Object_77.geometry} material={materials['Tires2.005']} />
                <mesh geometry={nodes.Object_78.geometry} material={materials['SCUDO_Yellow.005']} />
                <mesh geometry={nodes.Object_79.geometry} material={materials['Red_METAL.005']} />
                <mesh geometry={nodes.Object_80.geometry} material={materials['BRAKES_4K.005']} />
                <mesh geometry={nodes.Object_81.geometry} material={materials['Black_Metal.005']} />
                <mesh geometry={nodes.Object_82.geometry} material={materials['Black_METAL1.005']} />
                <mesh geometry={nodes.Object_83.geometry} material={materials['koplamp_binnen.008']} />
                <mesh geometry={nodes.Object_84.geometry} material={materials['mclaren_logo.004']} />
              </group>
            </group>
            <group position={[-1.38, 0.526, -4.889]} rotation={[-1.571, 0, 0]}>
              <group position={[1.38, -2.173, -0.526]} rotation={[Math.PI / 2, 0, 0]}>
                <mesh geometry={nodes.Object_87.geometry} material={materials['Silver_METAL.002']} />
                <mesh geometry={nodes.Object_88.geometry} material={materials['Tires2.002']} />
                <mesh geometry={nodes.Object_89.geometry} material={materials['SCUDO_Yellow.002']} />
                <mesh geometry={nodes.Object_90.geometry} material={materials['Red_METAL.002']} />
                <mesh geometry={nodes.Object_91.geometry} material={materials['BRAKES_4K.002']} />
                <mesh geometry={nodes.Object_92.geometry} material={materials['Black_Metal.002']} />
                <mesh geometry={nodes.Object_93.geometry} material={materials['Black_METAL1.002']} />
                <mesh geometry={nodes.Object_94.geometry} material={materials['koplamp_binnen.002']} />
                <mesh geometry={nodes.Object_95.geometry} material={materials['mclaren_logo.001']} />
              </group>
            </group>
            <group position={[1.323, 0.529, -0.784]} rotation={[-1.571, 0, 0]}>
              <group position={[-1.323, 1.932, -0.528]} rotation={[Math.PI / 2, 0, 0]}>
                <mesh geometry={nodes.Object_98.geometry} material={materials['Brake_Pad.004']} />
                <mesh geometry={nodes.Object_99.geometry} material={materials['Silver_METAL.004']} />
                <mesh geometry={nodes.Object_100.geometry} material={materials['Brake_Disc_1.004']} />
                <mesh geometry={nodes.Object_101.geometry} material={materials['Black_METAL.004']} />
                <mesh geometry={nodes.Object_102.geometry} material={materials['Black_MATTE.004']} />
              </group>
            </group>
            <group position={[-1.344, 0.529, -0.793]} rotation={[-1.571, 0, 0]}>
              <group position={[1.344, 1.924, -0.528]} rotation={[Math.PI / 2, 0, 0]}>
                <mesh geometry={nodes.Object_105.geometry} material={materials['Brake_Pad.003']} />
                <mesh geometry={nodes.Object_106.geometry} material={materials['Silver_METAL.003']} />
                <mesh geometry={nodes.Object_107.geometry} material={materials['Brake_Disc_1.003']} />
                <mesh geometry={nodes.Object_108.geometry} material={materials['Black_METAL.003']} />
                <mesh geometry={nodes.Object_109.geometry} material={materials['Black_MATTE.003']} />
              </group>
            </group>
            <group position={[1.346, 0.533, -4.715]} rotation={[-1.571, 0, 0]}>
              <group position={[-1.346, -1.998, -0.533]} rotation={[Math.PI / 2, 0, 0]}>
                <mesh geometry={nodes.Object_112.geometry} material={materials['Brake_Pad.005']} />
                <mesh geometry={nodes.Object_113.geometry} material={materials['Silver_METAL.005']} />
                <mesh geometry={nodes.Object_114.geometry} material={materials['Brake_Disc_1.005']} />
                <mesh geometry={nodes.Object_115.geometry} material={materials['Black_METAL.005']} />
                <mesh geometry={nodes.Object_116.geometry} material={materials['Black_MATTE.005']} />
                <mesh geometry={nodes.Object_117.geometry} material={materials['mini_brake.001']} />
              </group>
            </group>
            <group position={[-1.325, 0.533, -4.718]} rotation={[-1.571, 0, 0]}>
              <group position={[1.325, -2.002, -0.533]} rotation={[Math.PI / 2, 0, 0]}>
                <mesh geometry={nodes.Object_120.geometry} material={materials['Brake_Pad.002']} />
                <mesh geometry={nodes.Object_121.geometry} material={materials['Silver_METAL.002']} />
                <mesh geometry={nodes.Object_122.geometry} material={materials['Brake_Disc_1.002']} />
                <mesh geometry={nodes.Object_123.geometry} material={materials['Black_METAL.002']} />
                <mesh geometry={nodes.Object_124.geometry} material={materials['Black_MATTE.002']} />
                <mesh geometry={nodes.Object_125.geometry} material={materials.mini_brake} />
              </group>
            </group>
          </group>
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/models/mclaren/model.gltf')
