/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.3 model.gltf
Author: coOpsy (https://sketchfab.com/coOpsy)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/ninja-turtles-leonardo-toy-09b99b7941964c818969edf69a72e790
Title: Ninja Turtles "Leonardo" Toy
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export default function Toy4(props) {
  const { nodes, materials } = useGLTF('/models/ninja_turtles_leonardo_toy/model.gltf')
  return (
    <group {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]} scale={0.053}>
        <group rotation={[Math.PI / 2, 0, 0]}>
          <group rotation={[-Math.PI / 2, 0, 0]}>
            <mesh geometry={nodes.Ninja_Turtle_blank_8_0.geometry} material={materials.blank_8} />
            <mesh geometry={nodes.Ninja_Turtle_blank_8_0_1.geometry} material={materials.blank_8} />
            <mesh geometry={nodes.Ninja_Turtle_blank_8_0_2.geometry} material={materials.blank_8} />
          </group>
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/models/ninja_turtles_leonardo_toy/model.gltf')
